#!/bin/sh

php_script_version=7.4

MATCH="^[[:space:]]*($|;)"

echo "==== Additional PHP ${php_script_version} information ====" >&3
echo "" >&3
echo "++++ PHP @PHP_VERSION SAPI (php${php_script_version}query -S): ++++" >&3
/usr/sbin/php${php_script_version}query -S >&3
echo "" >&3
echo "++++ PHP ${php_script_version} Extensions (php${php_script_version}query -M -v): ++++" >&3
/usr/sbin/php${php_script_version}query -M -v >&3
echo "" >&3

echo "++++ Configuration files: ++++" >&3
for dsoname in calendar ctype exif fileinfo ftp gettext iconv pdo phar posix shmop sockets sysvmsg sysvsem sysvshm tokenizer; do
    inifile=${dsoname}.ini
    echo "**** /etc/php/${php_script_version}/mods-available/$dsoname.ini ****" >&3
    grep -Ev "$MATCH" "/etc/php/${php_script_version}/mods-available/$dsoname.ini" >&3
    echo "" >&3
done
